### ISSUE TITLE
paramètre pour identifiant publicitaire

### ISSUE THREAD

**Issue by matjmat** [EulerianTechnologies/eanalytics-flutter#2]
@edvincandon  il faut modifier la clé suivante : ea-flutter-adid
- devient  ea-android-adid si la plateforme est android
- devient  ea-ios-idfa si la plateforme est iOS

Car c'est dans celle-ci que nous récupérons les identifiants publicitaires (si autorisé) en fonction de la plateforme.

Merci.

**Comment by edvincandon** [comment]
ça marche @matjmat - je re-publish derrière.

**Comment by edvincandon** [comment]
@matjmat c'est released dans la 0.0.6

**Comment by matjmat** [comment]
Merci !
